__include__: [
  '../dfine/dfine_hgnetv2_x_coco.yml',
  '../base/rtv4.yml'
]

output_dir: ./outputs/rtv4_pill

eval_spatial_size: [640, 640]

num_classes: 56
remap_mscoco_category: False

train_dataloader:
  dataset:
    img_folder: ./dataset/images/train/
    ann_file: ./dataset/annotations/instances_train.json
    transforms:
      ops:
        - {type: Mosaic, output_size: 320, rotation_range: 10, translation_range: [0.1, 0.1], scaling_range: [0.5, 1.5],
           probability: 1.0, fill_value: 0, use_cache: False, max_cached_images: 50, random_pop: True}
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomZoomOut, fill: 0}
        - {type: RandomIoUCrop, p: 0.8}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [640, 640]}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
      policy:
        epoch: [4, 29, 50]
  collate_fn:
    mixup_epochs: [4, 29]
    stop_epoch: 50
    base_size: 640
    base_size_repeat: 1
  total_batch_size: 2
  num_workers: 0

val_dataloader:
  dataset:
    img_folder: ./dataset/images/val/
    ann_file: ./dataset/annotations/instances_val.json
    transforms:
      ops:
        - {type: Resize, size: [640, 640]}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
  total_batch_size: 2
  num_workers: 0

teacher_model:
  type: "DINOv3TeacherModel"
  dinov3_repo_path: ./dinov3/
  dinov3_weights_path: ./pretrain/dinov3_vitb16_pretrain_lvd1689m.pth
  patch_size: 16
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

HybridEncoder:
  distill_teacher_dim: 768

RTv4Criterion:
  weight_dict:
    loss_distill: 20
  distill_adaptive_params:
    enabled: True
    rho: 2
    delta: 0.25
    default_weight: 20

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.000005
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.
  lr: 0.0005
  betas: [0.9, 0.999]
  weight_decay: 0.000125

epoches: 58
flat_epoch: 29
no_aug_epoch: 8
